
# ~BrieFlow analysis configuration file~

# All paths are resolved relative to the directory the workflow is run from.

# Parameters:
all:
  root_fp: brieflow_output/
preprocess:
  sbs_samples_fp: config/sbs_samples.tsv
  sbs_combo_fp: config/sbs_combo.tsv
  phenotype_samples_fp: config/phenotype_samples.tsv
  phenotype_combo_fp: config/phenotype_combo.tsv
  sbs_data_format: nd2
  sbs_data_organization: tile
  sbs_channel_order: null
  sbs_channel_order_flip: true
  sbs_n_z_planes: null
  sbs_metadata_samples_df_fp: null
  phenotype_data_format: nd2
  phenotype_data_organization: tile
  phenotype_channel_order: null
  phenotype_channel_order_flip: true
  phenotype_round_order:
  - 1
  - 2
  phenotype_n_z_planes: null
  phenotype_metadata_samples_df_fp: null
  sample_fraction: 0.2
sbs:
  alignment_method: DAPI
  channel_names:
  - DAPI
  - G
  - T
  - A
  - C
  upsample_factor: 2
  window: 2
  skip_cycles_indices: null
  manual_background_cycle_index: null
  manual_channel_mapping: null
  extra_channel_indices:
  - 0
  max_filter_width: 3
  spot_detection_method: standard
  dapi_cycle: 1
  dapi_cycle_index: 0
  cyto_cycle: 1
  cyto_cycle_index: 0
  dapi_index: 0
  cyto_index: 1
  segmentation_method: cellpose
  gpu: false
  reconcile: contained_in_cells
  segment_cells: false
  df_barcode_library_fp: config/barcode_library.tsv
  threshold_peaks: 50
  call_reads_method: percentile
  bases:
  - G
  - T
  - A
  - C
  q_min: 0
  error_correct: true
  sort_calls: peak
  barcode_type: multi
  heatmap_plate: 6W
  heatmap_shape: 6W_sbs
  max_distance: 2
  map_start: 1
  map_end: 12
  map_col: prefix_map
  recomb_start: 13
  recomb_end: 14
  recomb_col: prefix_recomb
  recomb_filter_col: Q_recomb
  recomb_q_thresh: 0.1
  peak_width: 10
  nuclei_diameter: 8.368283871884005
  cell_diameter: 11.11324596323283
  nuclei_flow_threshold: 0.4
  nuclei_cellprob_threshold: 0.0
  cell_flow_threshold: 1
  cell_cellprob_threshold: 0
  cellpose_model: cyto3
phenotype:
  foci_channel_index:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
  - 8
  channel_names:
  - DAPI
  - ATACsee
  - H4Kacme
  - pSer5
  - KI67
  - H3K4me3
  - H3K27ac
  - pSer2
  - H3K9me3
  align: 'true'
  dapi_index: 0
  cyto_index: 4
  segmentation_method: cellpose
  reconcile: contained_in_cells
  gpu: false
  segment_cells: false
  cp_method: cp_emulator
  heatmap_plate: 6W
  heatmap_shape: 6W_ph
  nuclei_diameter: 43.49751675068879
  cell_diameter: 56.913279661307996
  nuclei_flow_threshold: 0.4
  nuclei_cellprob_threshold: 0.0
  cell_flow_threshold: 1
  cell_cellprob_threshold: 0
  cellpose_model: cyto3
  target: 0
  source: 5
  riders:
  - 6
  - 7
  - 8
  - 9
  remove_channel: source
  upsample_factor: 2
  window: 2
merge:
  approach: fast
  merge_combo_fp: config/merge_combo.tsv
  phenotype_dimensions:
  - 2400
  - 2400
  sbs_dimensions:
  - 1200
  - 1200
  sbs_metadata_cycle: 1
  score: 0.1
  threshold: 2
  sbs_metadata_channel: null
  ph_metadata_channel: null
  alignment_flip_x: false
  alignment_flip_y: false
  alignment_rotate_90: false
  sbs_dedup_prior:
    fov_distance_0: true
  pheno_dedup_prior:
    mapped_single_gene: false
    fov_distance_1: true
  initial_sbs_tiles:
  - 9
  - 23
  - 44
  - 85
  - 119
  - 174
  - 204
  - 254
  - 277
  - 319
  - 346
  det_range:
  - 0.06
  - 0.065
classify:
  classifier_path: brieflow_output/classifier/classifier/run_20260211_115358/models/multiclass_xgb_none/multiclass_xgb_none_model.dill
  confidence_thresholds:
    1:
      threshold: 0.97821
      mode: exclude
    2:
      threshold: 0.5
      mode: reassign
  metadata_cols_fp: config/cell_data_metadata_cols.tsv
  class_title: cell_stage
  class_mapping:
    label_to_class:
      1: Mitotic
      2: Interphase
